### PR TITLE
Add slack team id to enable opening the correct slack team #39

### PR DESCRIPTION
**Pull request by funmia**
Open Slack in the correct team #39 

The team ID can be gotten through the browser console under dev-tools as shown here: https://stackoverflow.com/a/44883343

### CODE REVIEW

**Comment by funmia** [comment]
@BasThomas Oh Okay, I didn't know. I'll try doing that instead.

**Comment by BasThomas** [comment]
Awesome! Let me know if I can help.

**Comment by BasThomas** [comment]
Now what you can do is run `pod update` which should update the data pod, allowing you to use the `slackID` in the app. 👍

**Comment by funmia** [comment]
I've just updated it and tested that it works correctly - deep links into the general channel.

**Pull request merged**
